### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ilyabreev** [razvanstanga/node-red-contrib-onvif#3]
When I trying to install `node-red-contrib-onvif` in Node-Red:

```
-----------------------------------------------------------
2020-11-24T19:57:50.231Z Install : node-red-contrib-onvif 1.0.1

2020-11-24T19:57:50.312Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-onvif@1.0.1
2020-11-24T19:58:10.085Z [out] 
2020-11-24T19:58:10.085Z [out] > sharp@0.26.3 install /config/node-red/node_modules/sharp
2020-11-24T19:58:10.085Z [out] > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
2020-11-24T19:58:10.085Z [out] 
2020-11-24T19:58:11.330Z [err] info
2020-11-24T19:58:11.333Z [err]  
2020-11-24T19:58:11.333Z [err] sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-linuxmusl-armv7.tar.br
2020-11-24T19:58:12.121Z [err] ERR!
2020-11-24T19:58:12.121Z [err]  sharp
2020-11-24T19:58:12.121Z [err]  Prebuilt libvips 8.10.0 binaries are not yet available for linuxmusl-armv7
2020-11-24T19:58:12.121Z [err] info
2020-11-24T19:58:12.122Z [err]  
2020-11-24T19:58:12.122Z [err] sharp Attempting to build from source via node-gyp but this may fail due to the above error
2020-11-24T19:58:12.122Z [err] info
2020-11-24T19:58:12.122Z [err]  sharp
2020-11-24T19:58:12.123Z [err]  Please see https://sharp.pixelplumbing.com/install for required dependencies
2020-11-24T19:58:18.878Z [err] gyp
2020-11-24T19:58:18.880Z [err]  
2020-11-24T19:58:18.881Z [err] ERR!
2020-11-24T19:58:18.881Z [err]  
2020-11-24T19:58:18.882Z [err] build error
2020-11-24T19:58:18.882Z [err]  
2020-11-24T19:58:18.885Z [err] gyp
2020-11-24T19:58:18.885Z [err]  
2020-11-24T19:58:18.886Z [err] ERR!
2020-11-24T19:58:18.887Z [err]  
2020-11-24T19:58:18.887Z [err] stack
2020-11-24T19:58:18.888Z [err]  Error: not found: make
2020-11-24T19:58:18.888Z [err] gyp
2020-11-24T19:58:18.888Z [err]  
2020-11-24T19:58:18.889Z [err] ERR!
2020-11-24T19:58:18.889Z [err]  
2020-11-24T19:58:18.889Z [err] stack
2020-11-24T19:58:18.890Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-11-24T19:58:18.890Z [err] gyp
2020-11-24T19:58:18.890Z [err]  
2020-11-24T19:58:18.891Z [err] ERR!
2020-11-24T19:58:18.891Z [err]  stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-11-24T19:58:18.891Z [err] gyp 
2020-11-24T19:58:18.891Z [err] ERR! 
2020-11-24T19:58:18.891Z [err] stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-11-24T19:58:18.892Z [err] gyp ERR! 
2020-11-24T19:58:18.892Z [err] stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-11-24T19:58:18.892Z [err] gyp ERR!
2020-11-24T19:58:18.892Z [err]  stack
2020-11-24T19:58:18.892Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-11-24T19:58:18.892Z [err] gyp
2020-11-24T19:58:18.892Z [err]  ERR! 
2020-11-24T19:58:18.893Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-11-24T19:58:18.893Z [err] gyp ERR!
2020-11-24T19:58:18.893Z [err]  stack     at FSReqCallback.oncomplete (fs.js:168:21)
2020-11-24T19:58:18.894Z [err] gyp
2020-11-24T19:58:18.894Z [err]  ERR! System Linux 4.19.127-v7
2020-11-24T19:58:18.895Z [err] gyp
2020-11-24T19:58:18.895Z [err]  ERR! 
2020-11-24T19:58:18.895Z [err] command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-11-24T19:58:18.895Z [err] gyp ERR!
2020-11-24T19:58:18.895Z [err]  cwd /config/node-red/node_modules/sharp
2020-11-24T19:58:18.895Z [err] gyp 
2020-11-24T19:58:18.895Z [err] ERR! node -v
2020-11-24T19:58:18.896Z [err]  v12.18.4
2020-11-24T19:58:18.896Z [err] gyp ERR!
2020-11-24T19:58:18.896Z [err]  node-gyp -v v5.1.0
2020-11-24T19:58:18.896Z [err] gyp 
2020-11-24T19:58:18.896Z [err] ERR! not ok
2020-11-24T19:58:18.896Z [err]  
2020-11-24T19:58:20.225Z [err] npm
2020-11-24T19:58:20.225Z [err]  
2020-11-24T19:58:20.226Z [err] ERR!
2020-11-24T19:58:20.226Z [err]  
2020-11-24T19:58:20.226Z [err] code
2020-11-24T19:58:20.227Z [err]  ELIFECYCLE
2020-11-24T19:58:20.227Z [err] npm
2020-11-24T19:58:20.227Z [err]  
2020-11-24T19:58:20.228Z [err] ERR!
2020-11-24T19:58:20.228Z [err]  
2020-11-24T19:58:20.228Z [err] errno
2020-11-24T19:58:20.229Z [err]  1
2020-11-24T19:58:20.251Z [err] npm
2020-11-24T19:58:20.251Z [err]  
2020-11-24T19:58:20.252Z [err] ERR!
2020-11-24T19:58:20.252Z [err]  sharp@0.26.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
2020-11-24T19:58:20.252Z [err] npm
2020-11-24T19:58:20.252Z [err]  
2020-11-24T19:58:20.253Z [err] ERR!
2020-11-24T19:58:20.253Z [err]  Exit status 1
2020-11-24T19:58:20.253Z [err] npm
2020-11-24T19:58:20.254Z [err]  
2020-11-24T19:58:20.254Z [err] ERR!
2020-11-24T19:58:20.254Z [err]  
2020-11-24T19:58:20.255Z [err] npm
2020-11-24T19:58:20.255Z [err]  
2020-11-24T19:58:20.255Z [err] ERR!
2020-11-24T19:58:20.255Z [err]  Failed at the sharp@0.26.3 install script.
2020-11-24T19:58:20.256Z [err] npm
2020-11-24T19:58:20.256Z [err]  
2020-11-24T19:58:20.257Z [err] ERR!
2020-11-24T19:58:20.257Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2020-11-24T19:58:20.332Z [err] 
2020-11-24T19:58:20.333Z [err] npm
2020-11-24T19:58:20.333Z [err]  
2020-11-24T19:58:20.334Z [err] ERR!
2020-11-24T19:58:20.334Z [err]  A complete log of this run can be found in:
2020-11-24T19:58:20.334Z [err] npm
2020-11-24T19:58:20.335Z [err]  
2020-11-24T19:58:20.335Z [err] ERR!
2020-11-24T19:58:20.335Z [err]      /root/.npm/_logs/2020-11-24T19_58_20_303Z-debug.log
2020-11-24T19:58:20.369Z rc=1
```

**Comment by razvanstanga** [comment]
Prebuilt libvips 8.10.0 binaries are not yet available for linuxmusl-armv7.
Please see https://sharp.pixelplumbing.com/install for required dependencies

On what device/OS are you running node red ?

**Comment by ilyabreev** [comment]
It's HassOS 4.17 on Raspberry Pi 3 B+

**Comment by LindGIT** [comment]
Same issue. looks sharp pack moved...
https://github.com/lovell/sharp-libvips/releases/

**Comment by razvanstanga** [comment]
It should work now. I tested it on a Raspberry pi zero / 3a+.

You should install it via command line `npm install node-red-contrib-onvif` as it takes a while to compile sharp. It also works from NodeRed `Manage Pallete`, but you have to hit Install sereveral times.
