### ISSUE TITLE
Installation via pallet failed

### ISSUE THREAD

**Issue by piranius-kas** [razvanstanga/node-red-contrib-onvif#6]
```
Installation via pallet failed.
Below is the web log file:
-----------------------------------------------------------
2021-12-27T09:11:06.840Z Установить : node-red-contrib-onvif 1.0.3

2021-12-27T09:11:06.930Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-onvif@1.0.3
2021-12-27T09:11:22.977Z [err] npm
2021-12-27T09:11:22.979Z [err]  
2021-12-27T09:11:22.979Z [err] ERR!
2021-12-27T09:11:22.980Z [err]  code
2021-12-27T09:11:22.980Z [err]  EAI_AGAIN
2021-12-27T09:11:22.981Z [err] npm
2021-12-27T09:11:22.981Z [err]  ERR!
2021-12-27T09:11:22.982Z [err]  
2021-12-27T09:11:22.982Z [err] errno EAI_AGAIN
2021-12-27T09:11:22.993Z [err] npm
2021-12-27T09:11:22.993Z [err]  ERR!
2021-12-27T09:11:22.993Z [err]  request to https://registry.npmjs.org/node-red-contrib-onvif failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443
2021-12-27T09:11:23.047Z [err] 
2021-12-27T09:11:23.048Z [err] npm
2021-12-27T09:11:23.048Z [err]  ERR!
2021-12-27T09:11:23.049Z [err]  A complete log of this run can be found in:
2021-12-27T09:11:23.049Z [err] npm 
2021-12-27T09:11:23.049Z [err] ERR!     /root/snap/node-red/675/.npm/_logs/2021-12-27T09_11_22_997Z-debug.log
2021-12-27T09:11:23.068Z rc=1
--------------------------------------------------------------------------
full log  /root/snap/node-red/675/.npm/_logs/2021-12-27T09_11_22_997Z-debug.log :
--------------------------------------------------------------------------
0 info it worked if it ends with ok
1 verbose cli [ '/snap/node-red/675/bin/node',
1 verbose cli   '/snap/node-red/675/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--no-audit',
1 verbose cli   '--no-update-notifier',
1 verbose cli   '--no-fund',
1 verbose cli   '--save',
1 verbose cli   '--save-prefix=~',
1 verbose cli   '--production',
1 verbose cli   'node-red-contrib-onvif@1.0.3' ]
2 info using npm@6.14.11
3 info using node@v10.23.3
4 verbose config Skipping project config: /root/snap/node-red/675/.npmrc. (matches userconfig)
5 verbose npm-session 843d05e85e8c26e1
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData error for node-red-contrib-onvif@1.0.3 request to https://registry.npmjs.org/node-red-contrib-onvif failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443
9 timing stage:rollbackFailedOptional Completed in 6ms
10 timing stage:runTopLevelLifecycles Completed in 13360ms
11 verbose type system
12 verbose stack FetchError: request to https://registry.npmjs.org/node-red-contrib-onvif failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443
12 verbose stack     at ClientRequest.req.on.err (/snap/node-red/675/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
12 verbose stack     at ClientRequest.emit (events.js:198:13)
12 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:401:9)
12 verbose stack     at TLSSocket.emit (events.js:198:13)
12 verbose stack     at emitErrorNT (internal/streams/destroy.js:91:8)
12 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
12 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
13 verbose cwd /root/snap/node-red/675
14 verbose Linux 5.4.0-91-generic
15 verbose argv "/snap/node-red/675/bin/node" "/snap/node-red/675/bin/npm" "install" "--no-audit" "--no-update-notifier" "--no-fund" "--save" "--save-prefix=~" "--production" "node-red-contrib-onvif@1.0.3"
16 verbose node v10.23.3
17 verbose npm  v6.14.11
18 error code EAI_AGAIN
19 error errno EAI_AGAIN
20 error request to https://registry.npmjs.org/node-red-contrib-onvif failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443
21 verbose exit [ 1, true ]

```

**Comment by razvanstanga** [comment]
I will replace sharp with jimp soon.
