### ISSUE TITLE
 error Failed at the sharp@0.30.3 install script

### ISSUE THREAD

**Issue by bastelbert** [razvanstanga/node-red-contrib-onvif#7]
Hi, I'm getting the following error messages during the installation of node-red-contrib-onvif:

3-20T17:22:11.056Z [out] > sharp@0.28.3 install /data/node_modules/sharp
2022-03-20T17:22:11.056Z [out] > (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
2022-03-20T17:22:11.056Z [out] 
2022-03-20T17:22:11.531Z [out] sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.6/libvips-8.10.6-linuxmusl-armv7.tar.br
2022-03-20T17:22:11.791Z [err] sharp: Installation error: Prebuilt libvips 8.10.6 binaries are not yet available for linuxmusl-armv7
2022-03-20T17:22:11.792Z [out] sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies

1129 verbose stack Error: sharp@0.30.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`
1129 verbose stack Exit status 1
1129 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
1129 verbose stack     at EventEmitter.emit (events.js:400:28)
1129 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1129 verbose stack     at ChildProcess.emit (events.js:400:28)
1129 verbose stack     at maybeClose (internal/child_process.js:1058:16)
1129 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
1130 verbose pkgid sharp@0.30.3
1131 verbose cwd /data
1132 verbose Linux 5.10.103-v7l+
1133 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sharp"
1134 verbose node v14.18.2
1135 verbose npm  v6.14.15
1136 error code ELIFECYCLE
1137 error errno 1
1138 error sharp@0.30.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`
1138 error Exit status 1
1139 error Failed at the sharp@0.30.3 install script.

**Comment by hardillb** [comment]
https://github.com/lovell/sharp/issues/3150

**Comment by razvanstanga** [comment]
I will replace sharp with jimp soon.
